replicaCount: 1

image:
  repository: tiffea/devops-project1
  pullPolicy: Always
  tag: "latest"

service:
  type: NodePort
  port: 5000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

postgresql:
  auth:
    username: postgres
    password: password123
    database: todos
