replicaCount: 3

image:
  repository: tiffea/devops-project1
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: NodePort
  port: 5000

ingress:
  enabled: false

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  timeoutSeconds: 5


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}

postgresql:
  auth:
    username: postgres
    existingSecret: devops-project1-db-secret
    database: todos
  primary:
    persistence:
      enabled: true
      size: 1Gi

#link to the existent file with actual secret
env:
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: devops-project1-db-secret
        key: database-url
