---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: devops-project1-db-secret
  namespace: default
spec:
  encryptedData:
    database-url: AgCCwyUBlEkK+hRf8/VIl6mIu+TQxwFKlHX2r/s+blfH5NiT24PC0FS8I86ZAdgCmpWeMw9RwPiQ4yCtpPoZKWpA49HsbHFHPG+l92wS7T9+qNloqFv1jAVxDwChwxvE6M3VrbWhlcuNtvM5PW1aimHNV1J/Tc1VW9lZDsEPQ99CegkyPRQ06SsoQ+281E6L1jbCul7XouZBXzIQ8JSrMxWSpmjVhTfTnPRpQqG84dGGhjjiNIPygaBBUYZ2HP9pJ70jTAQ+jwOo4H5PbIvF7J0Ub+KP0kB/OBii61XPZ89+N4qffw4OxPjhAhRBUABYHHE/85Co2hDeZ2ogy/4WKKGtOuwGMmzGgLBcW3PQW5we6yjS92dQLU0/mtLUd991WUkTW49EpuKAQsk7B6xpDMr/4AZAWYRTnr8NgK1UyH8AIfgu6AcBujhGLo9HFdn0wazTEFPO8kgQ4Vz7IUdxzmuK6RLZC15CFMXS0yBGoGxS3SoBfTapYVL/yEQ0zoRrJafew6P9EVuIF/6/khdQbJ2qw3itaDBkbKZo676G2dKm2OD7KI8QLw/t+Sp5UtPJWvELq2XQUQX5zxySVuQoKDp6Ukv8QLM7Hd1BhL7W0uF3qg1QOc+0wOIHju3srXBqK318h8qAR1/HITgY+8h6qSfFBklNNwpwfnr7FUuFtaWGBdviP9m+CTEas0BCqhla60/A/U0FBVQST49410+VXtGO5yud3tDo9Tkdq1DZa1KZ8xeYi6mcsj1ef/DS/bQdYfoLruypWevPFToCk7Vb8DKqfGEsK5nEl05YO5VgGooBmtF9UXtryTq13Ouu3g==
    postgres-password: AgCIApko2+m3oc4fm/MSLXMAQY527r5CLpSDDDJDRO9atCp+29BGg8lZPUR7BTbec7m6RYNpPxbNi8L3IbYFEWME5eg9db9tHhdgBEAbGF7Locl7kd2poJ7N0FOWqHtS3sdUjYRcnHWSJjdW1sAPJLxVfobwRWamldBs7YaumqS/+QPD1/ddCUEJg4SHQF7+DIJrcOZkSHW18mLs8CMHZUbVUYlqqlnO9GzAdRwG9gt8PSDxwwBeyikuaDgHHnpp1rls1lmYgu5xl8yeTf6gfjlDXkQh+SoNLP0Gx6OMu9rN7bXWhFSBWPlxPgljz/K7jNyvEP3FuaIQsfdYZ2vvYxyPrgYAAOdkzOEHdPTYfSQDyIYfcDiZGdqoZP/4xt+BMKpdwtcoYbPQl9mNjl/KemFqzGlSlo4pO3h8sxoGUiD7id7GRHNiZIshzoCdBTDn4V4s6hvDZ6XqRzWZDMTYQUpVxHjWFkskM24/GFnPso30e86/nKYmyeOvowH5gMQo9DwvNnPqJsyYopCSgAnzw4r5ufnUwqJMjxCMHv6jo6LG02jK9ggGVYXx0E/Rv3oNhMFme/yAZUBBCsXq3FNW4ylb5JeCppr2Iw/juu1vvN0CXv38mc8m+BLjDm+ySI68od1INYdKmmmFNCdHEwH+xBjDsvGiW8vtza/trI4wUhV12HRvS2+6ICkVojw9Kcptva9A8UnLkEkkoEvQuK5wSo28W1b97DELqbBbYnKXoP05eg==
  template:
    metadata:
      name: devops-project1-db-secret
      namespace: default
    type: Opaque
