[webservers]
devops-ec2 ansible_host=13.50.218.3 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-key.pem ansible_python_interpreter=/usr/bin/python3.12
[dbservers]
db-server ansible_host=i-01fc1da37e4c1bcb3 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-key.pem ansible_python_interpreter=/usr/bin/python3.12
[dbservers:vars]
ansible_ssh_common_args='-o ProxyCommand="sh -c \"aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters portNumber=%p\""'