---
- name: Deploy DevOps Project
  hosts: webservers
  become: true

  vars:
    project_dir: /home/ubuntu/devops_project1
    compose_file: docker-compose.prod.yml
    repo_url: https://github.com/Tiffea/devops_project1
    git_branch: main
    domain: tiffeadev.uk
    certbot_email: "{{ lookup('env', 'CERTBOT_EMAIL') }}"
    #you can hardcode your email or set an enviromental value
    #echo 'export CERTBOT_EMAIL="youremailwithsll@example.com"' >> ~/.zshrc && source ~/.zshrc
    postgres_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
    grafana_admin_password: "{{ lookup('env', 'GRAFANA_ADMIN_PASSWORD') }}"
    db_private_ip: 10.0.2.206

  roles:
    - common
    - docker
    - nginx
    - app
    - certbot

- name: deploy db-server
  hosts: dbservers
  become: true

  vars:
    compose_file_db: docker-compose-db.yml #empty variable name (no content)
    db_project_dir: /home/ubuntu/db
    postgres_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
  roles:
    - common
    - docker
    - postgres
#add q