apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: devops-project1 #where is it lives
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/Tiffea/devops_project1.git
    targetRevision: HEAD #the last commit
    path: helm-chart #argocd looks on this file in git repository
    helm:
      valueFiles:
        - values.prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true