name: Push to DockerHub; Deploy with Ansible

on:
  push:
    branches:
      - main
      - stage

jobs:
  secret-scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          #restriction for checkout not for scanner
      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: secret-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker Image (locally)
        uses: docker/build-push-action@v5
        with:
          context: ./app #take the dockerfile from this dir
          push: false
          load: true
          tags: tiffea/devops-project1:latest

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: tiffea/devops-project1:latest
          format: table
          exit-code: '1'
          severity: CRITICAL
      
      - name: Push docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: tiffea/devops-project1:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions: #only this part has rights to change sequrity group
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ID }}:role/github_worker
          aws-region: eu-north-1

      - name: Get runner public IP
        id: ip #tag
        run: echo "ip=$(curl -s https://checkip.amazonaws.com)" >> $GITHUB_OUTPUT #AWS must be available

      - name: Open SSH for runner IP
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.AWS_SG_ID }} \
            --protocol tcp --port 22 \
            --cidr ${{ steps.ip.outputs.ip }}/32

      - name: Install Ansible
        run: pip install ansible
      
      - name: install plugin for ssm-agent session in CLI
        run: |
          curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" \
          -o "session-manager-plugin.deb"
          sudo dpkg -i session-manager-plugin.deb

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/devops-key.pem
          chmod 600 ~/.ssh/devops-key.pem
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

        #conciously make the step of creation the same folder just to know from logs what step caused problem if deploy fell
      - name: Configure SSH for SSM tunnel
        run: |
          mkdir -p ~/.ssh
          cat >> ~/.ssh/config << 'EOF'
          Host i-* mi-*
              ProxyCommand sh -c "aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters portNumber=%p"
              StrictHostKeyChecking no
          EOF

      - name: Test SSH connection
        run: |
          ssh -i ~/.ssh/devops-key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.SSH_HOST }} "echo connected"

      - name: Deploy with Ansible
        run: |
          ansible-playbook -i infra/ansible/inventory.ini infra/ansible/site.yml \
          -e "certbot_email=${{ secrets.SECRET_EMAIL }}" \
          -e "postgres_password=${{ secrets.POSTGRES_PASSWORD }}" \
          -e "grafana_admin_password=${{ secrets.GRAFANA_ADMIN_PASSWORD }}" \
          -e "git_branch=${{ github.ref_name }}"

      - name: Re-configure AWS credentials before cleanup
        if: always()
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ID }}:role/github_worker
          aws-region: eu-north-1

      - name: Close SSH for runner IP
        if: always()
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.AWS_SG_ID }} \
            --protocol tcp --port 22 \
            --cidr ${{ steps.ip.outputs.ip }}/32

# Jobs are not separated into build/deploy stages because there is only one contributor and one branch.
# change when staging environment or team is added.